# Generated by Django 3.0.4 on 2021-03-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210306_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answers',
            field=models.ManyToManyField(to='api.Answer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(related_name='posts_upvoted', to='api.User'),
        ),
    ]
