# Generated by Django 3.1.7 on 2021-03-07 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210306_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled',
            old_name='class_id',
            new_name='enrolled_class',
        ),
        migrations.RenameField(
            model_name='enrolled',
            old_name='user_id',
            new_name='user',
        ),
    ]
