# Generated by Django 3.1.7 on 2021-03-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210307_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled',
            old_name='class_id',
            new_name='enrolled_class',
        ),
        migrations.RenameField(
            model_name='enrolled',
            old_name='user_id',
            new_name='user',
        ),
    ]
