# Generated by Django 3.0.4 on 2021-03-07 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210307_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='class_in',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='posts_visited', to=settings.AUTH_USER_MODEL),
        ),
    ]
