# Generated by Django 3.0.4 on 2021-03-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210307_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='enrolles',
            new_name='enrollees',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='viewed',
            new_name='views',
        ),
    ]
