# Generated by Django 3.1.7 on 2021-03-07 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210307_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers_post', to='api.post'),
        ),
    ]
