# Generated by Django 3.1.7 on 2021-03-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210307_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='answers_post', to='api.post'),
        ),
    ]
