# Generated by Django 3.1.7 on 2021-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210307_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
